### ISSUE TITLE
Keep listening for messages

### ISSUE THREAD

**Issue by PeterBurner** [mikeokner/posix-mq#5]
When running the following code the node script exits after all available messages have been read. Is this behaviour intended? I would like it to keep listening for new messages.

```
var mq = new PosixMQ();
var readbuf = new Buffer(mq.msgsize);
mq.on('messages', function() {
    var n;
    while ((n = this.shift(readbuf)) !== false) {
        console.log("Received message ("+ n +" bytes): "+ readbuf.toString('utf8', 0, n));
        console.log("Messages left: "+ this.curmsgs);
    }
});
mq.open({name: '/pmqtest'});
```

**Comment by PeterBurner** [comment]
if I open the queue first an then start listening I get the same behaviour as described in #1  
```
var mq = new PosixMQ();
mq.open({name: '/pmqtest'});
var readbuf = new Buffer(mq.msgsize);
mq.on('messages', function() {
    var n;
    while ((n = this.shift(readbuf)) !== false) {
        console.log("Received message ("+ n +" bytes): "+ readbuf.toString('utf8', 0, n));
        console.log("Messages left: "+ this.curmsgs);
    }
});
```

**Comment by mikeokner** [comment]
Peter,

I believe this issue is largely due to quirky behavior in the underlying queue architecture. Someone else recently pointed out to me that if you look at the man page for [mq_notify](https://www.systutorials.com/docs/linux/man/3-mq_notify/), it states:

> Message notification occurs only when a new message arrives and the queue was previously empty. If the queue was not empty at the time mq_notify() was called, then a notification will occur only after the queue is emptied and a new message arrives.

So the remedy here is pretty much the same as what has to be done for 'native' code: read the queue until it's empty, _then_ execute the `mq.on` listener.

It's something I intend to revisit in order to update the README for this library and/or implement a workaround, but for now manually draining the queue before attaching the listener should work.

**Comment by sonu461993** [comment]
@mikeokner It's not working... :(

const PosixMQ = require('posix-mq');
const {app} = require('electron');

var mq = new PosixMQ();

mq.open({
    name: '/pmqtest1',
	create: false,
    mode: '0777',
    maxmsgs: 20,
    msgsize: 30,
	exclusive: true
});

let readbuf = new Buffer.alloc(mq.msgsize);

mq.on('drain', showMsgFromQueue);

function showMsgFromQueue(){
    let n;
	console.log('message queue function')
    while ((n = this.shift(readbuf)) !== false) {
        console.log("Received message ("+ n +" bytes): "+ readbuf.toString('utf8', 0, n));
        console.log("Messages left: "+ this.curmsgs);
		app.emit('queueMessage', readbuf.toString('utf8', 0, n));

		if(this.curmsgs == 0){
				console.log('empty list')
				mq.on('messages', showMsgFromQueue);
		}

	}
}

**Comment by mikeokner** [comment]
@sonu461993 without more information regarding what specifically isn't working I can't be of much help, but I do think it's probably a bad idea to call `mq.on('messages', func)` a second time inside your handler function.

**Comment by abhishekchauhan4693** [comment]
@mikeokner thanks for giving your precious time here.... I'm also facing the same issue @PeterBurner mentioned here... So I tried what you explained above to bind the event listener when queue is empty but it's not working... It's giving the same result...

Thanks in advance

**Comment by mikeokner** [comment]
@abhishekchauhan4693 I've tested that this works regardless of whether there are already messages in the queue or not. Can you verify you are doing something similar, and share a code snippet to reproduce the issue if you still have problems?

```javascript
const PosixMQ = require('posix-mq');
const readChannel = new PosixMQ();

// Open the queue and allocate the buffer to read messages into
readChannel.open({
    name: '/test',
    create: true,
    mode: '0777',
    maxmsgs: 10,
    msgsize: 256
});
readbuf = Buffer.alloc(readChannel.msgsize);
console.log('readChannel opened');
console.log('--------------------------------------');

// Define the handler function to read all messages currently in the queue
handleMsg = () => {
    var n;
    while ((n = readChannel.shift(readbuf)) !== false) {
        var msg = readbuf.toString('utf8', 0, n);
        console.log('read: ' + msg)
    }
};

// Call the handler function once before binding the handler to ensure
// all existing messages are read
handleMsg();

// Bind the handler now that the queue has been emptied by the previous invocation
readChannel.on('messages', handleMsg);
```

**Comment by sonu461993** [comment]
> @abhishekchauhan4693 I've tested that this works regardless of whether there are already messages in the queue or not. Can you verify you are doing something similar, and share a code snippet to reproduce the issue if you still have problems?
> 
> ```js
> const PosixMQ = require('posix-mq');
> const readChannel = new PosixMQ();
> 
> // Open the queue and allocate the buffer to read messages into
> readChannel.open({
>     name: '/test',
>     create: true,
>     mode: '0777',
>     maxmsgs: 10,
>     msgsize: 256
> });
> readbuf = Buffer.alloc(readChannel.msgsize);
> console.log('readChannel opened');
> console.log('--------------------------------------');
> 
> // Define the handler function to read all messages currently in the queue
> handleMsg = () => {
>     var n;
>     while ((n = readChannel.shift(readbuf)) !== false) {
>         var msg = readbuf.toString('utf8', 0, n);
>         console.log('read: ' + msg)
>     }
> };
> 
> // Call the handler function once before binding the handler to ensure
> // all existing messages are read
> handleMsg();
> 
> // Bind the handler now that the queue has been emptied by the previous invocation
> readChannel.on('messages', handleMsg);
> ```

Thank you so much @mikeokner .... It works..!!!

**Comment by PeterBurner** [comment]
@mikeokner yes the snippet you posted works fine. It's just that the example code in the README doesn't.  
Could you please replace the example? It's confusing.  
The order of calls is important.  
1. call `open`
2. read all pre-existing messages
3. set the listener for new messages

**Comment by mikeokner** [comment]
@PeterBurner I have taken your advice and added the snippet above to the README. Hopefully that reduces confusion in the future!

**Comment by sonu461993** [comment]
@mikeokner Thanks for solution... One more issue I'm facing right now is after getting certain messages event will stop listening. For example I have run the application then I'm receiving the message but after getting 50-100 messages the function itself stop getting call.

My code is: 


const PosixMQ = require('posix-mq');
const {app} = require('electron');

var mq = new PosixMQ();

mq.open({
    name: '/pmqtest1',
	create: false,
    mode: '0777',
    maxmsgs: 200,
    msgsize: 300
});



let readbuf = new Buffer.alloc(mq.msgsize);

function showMsgFromQueue(){
    let n;
	console.log('function call')
try{
console.log(readbuf.length)
    while ((n = mq.shift(readbuf)) !== false) {
        console.log("Received message ("+ n +" bytes): "+ readbuf.toString('utf8', 0, n));
        console.log("Messages left: "+ mq.curmsgs);
		app.emit('receiveMessage', readbuf.toString('utf8', 0, n));
	}

}

catch(e)
{
console.log(e.message);
}
		
}

showMsgFromQueue();
mq.on('messages', showMsgFromQueue);



It's not throwing any error too. Can you please add one event for error so if any error is there it should invoke error event?

**Comment by PeterBurner** [comment]
@mikeokner Thanks a lot!  
my issue is resolved with this
